"""Cookie manager for platform video downloaders.

Provides cookies to yt-dlp via Netscape-format cookie files.

Sources (in priority order):
1. EXTENSION — cookies pushed from the Chrome extension via save_from_extension()
2. FILE      — manually placed Netscape cookie file in storage/cookies/
3. CHROME    — auto-read from Chrome profile using browser-cookie3
4. NONE      — no cookies available

Main use case:
    manager = CookieManager()
    cookie_path = manager.get_cookie_file("bilibili")
    # Pass to yt-dlp: --cookies <cookie_path>
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# ─── Platform → domain mapping ────────────────────────────────────────────────

PLATFORM_DOMAINS: dict[str, str] = {
    "bilibili": ".bilibili.com",
    "douyin": ".douyin.com",
    "tiktok": ".tiktok.com",
}


# ─── Enums & dataclasses ──────────────────────────────────────────────────────


class CookieSource(str, Enum):
    """Where a cookie entry came from."""

    CHROME = "chrome"
    FILE = "file"
    EXTENSION = "extension"
    NONE = "none"


@dataclass
class CookieEntry:
    """A stored cookie entry for a platform.

    Attributes:
        platform:    Platform identifier, e.g. "bilibili".
        cookie_str:  Raw cookie string in ``key=value; key2=value2`` format.
        source:      Where the cookie came from.
        captured_at: Unix timestamp when the cookie was captured.
    """

    platform: str
    cookie_str: str
    source: CookieSource
    captured_at: float = field(default_factory=time.time)


# ─── Helpers ──────────────────────────────────────────────────────────────────


def format_cookie_string(cookies: list[dict]) -> str:
    """Format a list of cookie dicts as a ``key=value; ...`` string.

    Args:
        cookies: List of dicts with at least ``name`` and ``value`` keys.

    Returns:
        Cookie string suitable for an HTTP ``Cookie`` header.
    """
    parts: list[str] = []
    for c in cookies:
        name = c.get("name", "")
        value = c.get("value", "")
        if name:
            parts.append(f"{name}={value}")
    return "; ".join(parts)


def _write_netscape_file(cookies: list[dict], output_path: Path) -> None:
    """Write cookies to a Netscape-format cookie file.

    The Netscape format is:
        # Netscape HTTP Cookie File
        <domain> <flag> <path> <secure> <expiry> <name> <value>

    Args:
        cookies:     List of cookie dicts (from browser-cookie3 or parsed).
        output_path: Destination file path.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Netscape HTTP Cookie File", "# Generated by AIFlow CookieManager", ""]
    for c in cookies:
        domain = c.get("domain", "")
        # Ensure domain starts with a dot for subdomain matching
        if domain and not domain.startswith("."):
            domain = "." + domain
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expiry = int(c.get("expires", 0) or 0)
        name = c.get("name", "")
        value = c.get("value", "")
        if name:
            lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}")
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _parse_netscape_file(file_path: Path) -> list[dict]:
    """Parse a Netscape cookie file into a list of cookie dicts.

    Args:
        file_path: Path to the Netscape cookie file.

    Returns:
        List of cookie dicts with keys: domain, flag, path, secure, expires, name, value.
    """
    cookies: list[dict] = []
    try:
        text = file_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return cookies

    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) < 7:
            continue
        domain, flag, path, secure, expiry, name, value = parts[:7]
        cookies.append({
            "domain": domain,
            "flag": flag,
            "path": path,
            "secure": secure.upper() == "TRUE",
            "expires": int(expiry) if expiry.isdigit() else 0,
            "name": name,
            "value": value,
        })
    return cookies


# ─── CookieManager ────────────────────────────────────────────────────────────


class CookieManager:
    """Manage platform cookies for authenticated video downloads.

    Cookies are stored as Netscape-format files in ``storage_dir/{platform}.txt``.
    These files can be passed directly to yt-dlp via ``--cookies``.

    Priority when reading cookies:
    1. Extension-pushed cookies (most recent)
    2. Manually placed file
    3. Chrome auto-read via browser-cookie3

    Args:
        storage_dir: Directory for cookie files. Defaults to ``storage/cookies``.
    """

    def __init__(self, storage_dir: Path = Path("storage/cookies")) -> None:
        self._storage_dir = storage_dir
        self._storage_dir.mkdir(parents=True, exist_ok=True)
        # In-memory cache: platform → CookieEntry
        self._cache: dict[str, CookieEntry] = {}

    # ── Public API ────────────────────────────────────────────────────────────

    def get_cookies(self, platform: str) -> Optional[CookieEntry]:
        """Get the best available cookies for a platform.

        Checks sources in priority order: EXTENSION → FILE → CHROME.

        Args:
            platform: Platform identifier (e.g. "bilibili").

        Returns:
            :class:`CookieEntry` if cookies are available, else ``None``.
        """
        # 1. In-memory cache (extension-pushed or recently loaded)
        if platform in self._cache:
            return self._cache[platform]

        # 2. File on disk
        file_path = self._cookie_file_path(platform)
        if file_path.is_file():
            cookies = _parse_netscape_file(file_path)
            if cookies:
                cookie_str = format_cookie_string(cookies)
                entry = CookieEntry(
                    platform=platform,
                    cookie_str=cookie_str,
                    source=CookieSource.FILE,
                )
                self._cache[platform] = entry
                return entry

        # 3. Chrome auto-read
        if self.load_from_chrome(platform):
            return self._cache.get(platform)

        return None

    def get_cookie_file(self, platform: str) -> Optional[Path]:
        """Get the path to the Netscape cookie file for yt-dlp.

        Ensures the file exists (loading from Chrome if needed).

        Args:
            platform: Platform identifier.

        Returns:
            Path to the ``.txt`` cookie file, or ``None`` if unavailable.
        """
        file_path = self._cookie_file_path(platform)
        if file_path.is_file():
            return file_path

        # Try to populate from Chrome
        if self.load_from_chrome(platform):
            if file_path.is_file():
                return file_path

        return None

    def save_from_extension(self, platform: str, cookie_str: str) -> None:
        """Save cookies received from the browser extension.

        Stores the raw cookie string in memory and writes a Netscape file
        so yt-dlp can use it.

        Args:
            platform:   Platform identifier.
            cookie_str: Raw ``key=value; key2=value2`` cookie string.
        """
        entry = CookieEntry(
            platform=platform,
            cookie_str=cookie_str,
            source=CookieSource.EXTENSION,
        )
        self._cache[platform] = entry

        # Convert key=value string to cookie dicts and write Netscape file
        cookies = _parse_cookie_string(cookie_str)
        domain = PLATFORM_DOMAINS.get(platform, f".{platform}.com")
        cookie_dicts = [
            {"domain": domain, "path": "/", "secure": True, "expires": 0,
             "name": name, "value": value}
            for name, value in cookies
        ]
        output_path = self._cookie_file_path(platform)
        _write_netscape_file(cookie_dicts, output_path)
        logger.info("Saved extension cookies for %s → %s", platform, output_path)

    def load_from_file(self, platform: str, file_path: Path) -> None:
        """Load cookies from an existing Netscape cookie file.

        Copies the file to the managed storage directory and updates the cache.

        Args:
            platform:  Platform identifier.
            file_path: Path to the source Netscape cookie file.

        Raises:
            FileNotFoundError: If ``file_path`` does not exist.
            ValueError: If the file cannot be parsed as a Netscape cookie file.
        """
        if not file_path.is_file():
            raise FileNotFoundError(f"Cookie file not found: {file_path}")

        cookies = _parse_netscape_file(file_path)
        if not cookies:
            raise ValueError(f"No valid cookies found in: {file_path}")

        dest = self._cookie_file_path(platform)
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(file_path.read_bytes())

        cookie_str = format_cookie_string(cookies)
        entry = CookieEntry(
            platform=platform,
            cookie_str=cookie_str,
            source=CookieSource.FILE,
        )
        self._cache[platform] = entry
        logger.info("Loaded cookies from file for %s → %s", platform, dest)

    def load_from_chrome(self, platform: str) -> bool:
        """Try to read cookies from Chrome using browser-cookie3.

        Gracefully returns ``False`` if browser-cookie3 is not installed,
        Chrome is not running, or the domain is not found.

        Args:
            platform: Platform identifier.

        Returns:
            ``True`` if cookies were successfully loaded, ``False`` otherwise.
        """
        domain = PLATFORM_DOMAINS.get(platform)
        if not domain:
            logger.debug("No domain mapping for platform: %s", platform)
            return False

        try:
            import browser_cookie3  # type: ignore[import]
        except ImportError:
            logger.debug("browser-cookie3 not installed; skipping Chrome cookie read")
            return False

        try:
            # browser_cookie3.chrome() returns an http.cookiejar.CookieJar
            cj = browser_cookie3.chrome(domain_name=domain.lstrip("."))
            cookie_list = list(cj)
            if not cookie_list:
                logger.debug("No Chrome cookies found for domain: %s", domain)
                return False

            # Convert CookieJar cookies to dicts
            cookie_dicts = [
                {
                    "domain": getattr(c, "domain", domain),
                    "path": getattr(c, "path", "/"),
                    "secure": getattr(c, "secure", False),
                    "expires": int(getattr(c, "expires", 0) or 0),
                    "name": c.name,
                    "value": c.value,
                }
                for c in cookie_list
            ]

            # Write Netscape file
            output_path = self._cookie_file_path(platform)
            _write_netscape_file(cookie_dicts, output_path)

            cookie_str = format_cookie_string(cookie_dicts)
            entry = CookieEntry(
                platform=platform,
                cookie_str=cookie_str,
                source=CookieSource.CHROME,
            )
            self._cache[platform] = entry
            logger.info(
                "Loaded %d Chrome cookies for %s → %s",
                len(cookie_dicts), platform, output_path,
            )
            return True

        except Exception as exc:  # noqa: BLE001
            logger.debug("Failed to read Chrome cookies for %s: %s", platform, exc)
            return False

    def export_netscape(self, platform: str, output_path: Path) -> bool:
        """Export cookies for a platform as a Netscape-format file.

        Args:
            platform:    Platform identifier.
            output_path: Destination file path.

        Returns:
            ``True`` if exported successfully, ``False`` if no cookies available.
        """
        source_path = self._cookie_file_path(platform)
        if source_path.is_file():
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_bytes(source_path.read_bytes())
            logger.info("Exported cookies for %s → %s", platform, output_path)
            return True

        # Try loading first
        entry = self.get_cookies(platform)
        if entry is None:
            return False

        source_path = self._cookie_file_path(platform)
        if source_path.is_file():
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_bytes(source_path.read_bytes())
            return True

        return False

    def list_available(self, platform: str) -> list[CookieSource]:
        """List which cookie sources are available for a platform.

        Checks each source without loading/caching.

        Args:
            platform: Platform identifier.

        Returns:
            List of available :class:`CookieSource` values (may be empty).
        """
        available: list[CookieSource] = []

        # Extension: check in-memory cache
        entry = self._cache.get(platform)
        if entry and entry.source == CookieSource.EXTENSION:
            available.append(CookieSource.EXTENSION)

        # File: check disk
        if self._cookie_file_path(platform).is_file():
            # Determine actual source from cache if known
            if entry and entry.source == CookieSource.FILE:
                available.append(CookieSource.FILE)
            elif CookieSource.EXTENSION not in available:
                available.append(CookieSource.FILE)

        # Chrome: check if browser-cookie3 is importable
        try:
            import browser_cookie3  # type: ignore[import]  # noqa: F401
            available.append(CookieSource.CHROME)
        except ImportError:
            pass

        return available

    def clear_cache(self, platform: Optional[str] = None) -> None:
        """Clear the in-memory cookie cache.

        Args:
            platform: If given, clear only that platform. Otherwise clear all.
        """
        if platform is not None:
            self._cache.pop(platform, None)
        else:
            self._cache.clear()

    # ── Private helpers ───────────────────────────────────────────────────────

    def _cookie_file_path(self, platform: str) -> Path:
        """Return the managed Netscape cookie file path for a platform."""
        return self._storage_dir / f"{platform}.txt"


# ─── Internal helpers ─────────────────────────────────────────────────────────


def read_cookie_string(file_path: Optional[Path]) -> str:
    """Read a Netscape cookie file and return a ``key=value; ...`` header string.

    Args:
        file_path: Path to a Netscape-format cookie file, or ``None``.

    Returns:
        Cookie header string suitable for an HTTP ``Cookie`` header, or an
        empty string when *file_path* is ``None`` / missing / unparseable.
    """
    if file_path is None:
        return ""
    file_path = Path(file_path)
    if not file_path.is_file():
        return ""
    cookies = _parse_netscape_file(file_path)
    return format_cookie_string(cookies)


def _parse_cookie_string(cookie_str: str) -> list[tuple[str, str]]:
    """Parse a ``key=value; key2=value2`` cookie string into (name, value) pairs.

    Args:
        cookie_str: Raw cookie string.

    Returns:
        List of ``(name, value)`` tuples.
    """
    pairs: list[tuple[str, str]] = []
    for part in cookie_str.split(";"):
        part = part.strip()
        if not part:
            continue
        if "=" in part:
            name, _, value = part.partition("=")
            pairs.append((name.strip(), value.strip()))
    return pairs
