import { useState } from "react";
import { Link } from "react-router-dom";
import { studioRequest } from "../pages/StudioSettings";
export default function ProductionActions({ projectId, kind, scenes, onChanged }: { projectId: number; kind: string; scenes: { id: number; order: number }[]; onChanged: () => Promise<void> }) {
  const [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [scene, setScene] = useState("");
  const [history, setHistory] = useState<{ request_id: string; status: string; error: string }[]>([]);
  const button = "rounded-lg border border-white/20 px-4 py-2 text-sm disabled:opacity-40";
  async function act(path: string, body?: unknown) { setBusy(true); setMessage(""); try { const result = await studioRequest<{ status?: string; error?: string; message?: string }>(path, "POST", body); setMessage(result.error || result.message || result.status || "Đã hoàn tất; xem và duyệt kết quả bên dưới."); await onChanged(); } catch (e) { setMessage(String(e)); } finally { setBusy(false); } }
  if (kind === "legacy") return <section className="space-y-3 rounded-xl border border-white/10 p-4"><h3 className="font-semibold">Dự án chưa phân loại</h3><p className="text-sm text-zinc-400">Mở Timeline để tiếp tục luồng cũ, hoặc xác nhận loại video bên trên để dùng xưởng sản xuất.</p><Link className={button} to={`/timeline/${projectId}`}>Timeline & Flow</Link></section>;
  return <section className="space-y-3 rounded-xl border border-white/10 p-4"><h3 className="font-semibold">Tạo và nhận tài nguyên</h3><div className="flex flex-wrap gap-3"><Link className={button} to={`/connections?project=${projectId}`}>Tạo / tiếp tục lời đọc</Link><Link className={button} to={`/timeline/${projectId}`}>Timeline & Flow</Link><Link className={button} to="/studio-settings">Provider & thư viện</Link>{kind === "video" && <button className={button} disabled={busy} onClick={() => void act(`/studio/projects/${projectId}/collect-clips`)}>Nhận clip từ Timeline vào xưởng</button>}</div>{kind === "video" && <label className="block text-sm">Cảnh cần tạo ảnh<select className="ml-2 rounded bg-zinc-900 p-2" value={scene} onChange={e => setScene(e.target.value)}><option value="">Chọn cảnh</option>{scenes.map(s => <option key={s.id} value={s.id}>Cảnh {s.order + 1}</option>)}</select></label>}<button className={button} disabled={busy || (kind === "video" && !scene)} onClick={() => void act(`/studio/projects/${projectId}/generate-image`, { request_id: crypto.randomUUID(), scene_id: kind === "video" ? Number(scene) : null })}>{busy ? "Đang xử lý…" : "Tạo ảnh bằng provider đã cấu hình"}</button><p className="text-xs text-zinc-400">Ảnh được gửi tới Gemini cùng tham chiếu của dự án; dùng quota/billing đã cấu hình. Kết quả cần duyệt, không tự xuất.</p><button className={button} disabled={busy} onClick={() => { void studioRequest<typeof history>(`/studio/projects/${projectId}/operations`).then(setHistory).catch(e => setMessage(String(e))); }}>Xem trạng thái các lần tạo ảnh</button><ul className="space-y-1 text-xs">{history.map(h => <li key={h.request_id}>{h.request_id.slice(0, 8)} · {h.status} {h.error}</li>)}</ul><p role="status" className="text-sm text-amber-200">{message}</p></section>;
}
