import { useEffect, useRef, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { studioRequest } from "../pages/StudioSettings";
const button = "rounded-lg border border-white/20 px-3 py-2 text-sm disabled:opacity-40";
const field = "w-full rounded-lg border border-white/15 bg-zinc-900 p-3 text-sm";
type Row = { file: string; text: string; include: boolean; reviewed: boolean; duration: number; source: string };
type Run = { run_id: string; epochs: number; has_sample: boolean; can_resume: boolean; profile: { name: string; status: string } | null; progress: { step: number; total_steps: number } | null };
type Detail = { job_id: string; selection: { voice_name: string }; has_dataset: boolean; dataset_approved: boolean; runs: Run[]; actions: { request_id: string; status: string; error?: string; input: { kind: string } }[] };
const endpoint = "/training-control";
export default function TrainingControl({ incomingJob = "" }: { incomingJob?: string }) {
  const [params, setParams] = useSearchParams();
  const job = params.get("training") || "";
  const activeJob = useRef(job);
  activeJob.current = job;
  const [connected, setConnected] = useState(false), [url, setUrl] = useState(""), [token, setToken] = useState("");
  const [jobs, setJobs] = useState<{ job_id: string; voice_name: string }[]>([]), [detail, setDetail] = useState<Detail | null>(null);
  const [busy, setBusy] = useState(false), [remoteBusy, setRemoteBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const [review, setReview] = useState<{ hash: string; rows: Row[] }>({ hash: "", rows: [] }), [index, setIndex] = useState(0), [edit, setEdit] = useState<Row | null>(null);
  const [epochs, setEpochs] = useState(3), [sampleText, setSampleText] = useState("Xin chào, đây là câu nghe thử chưa xuất hiện trong dữ liệu huấn luyện.");
  const [heard, setHeard] = useState<string[]>([]);
  function selectJob(id: string) { const next = new URLSearchParams(params); if (id) next.set("training", id); else next.delete("training"); setParams(next); }
  useEffect(() => { if (incomingJob) selectJob(incomingJob); }, [incomingJob]);
  useEffect(() => { studioRequest<{ configured: boolean; url: string }>(`${endpoint}/connection`).then(s => { setConnected(s.configured); setUrl(s.url); }).catch(e => setError(String(e))); }, []);
  async function refresh() {
    if (!connected) return;
    const [health, listing, selected] = await Promise.all([studioRequest<{ busy: boolean }>(`${endpoint}/remote/health`), studioRequest<typeof jobs>(`${endpoint}/remote/jobs`), job ? studioRequest<Detail>(`${endpoint}/remote/jobs/${job}`) : Promise.resolve(null)]);
    if (activeJob.current !== job) return;
    setRemoteBusy(health.busy); setJobs(listing); setDetail(selected);
  }
  useEffect(() => { let stopped = false, polling = false; async function poll() { if (polling || !connected) return; polling = true; try { if (!stopped) await refresh(); } catch (e) { if (!stopped) setError(String(e)); } finally { polling = false; } } void poll(); const timer = window.setInterval(() => void poll(), 5000); return () => { stopped = true; clearInterval(timer); }; }, [connected, job]);
  useEffect(() => { setReview({ hash: "", rows: [] }); setIndex(0); setEdit(null); setHeard([]); }, [job]);
  async function act(fn: () => Promise<unknown>) { setBusy(true); setError(""); setNotice(""); try { await fn(); await refresh(); } catch (e) { setError(String(e)); } finally { setBusy(false); } }
  async function readReview() { const data = await studioRequest<typeof review>(`${endpoint}/remote/jobs/${job}/review`); if (activeJob.current !== job) return; setReview(data); setIndex(0); setEdit(data.rows[0] || null); }
  function action(kind: string, run_id = "") { return act(async () => { const resumeEpochs = detail?.runs.find(r => r.run_id === run_id)?.epochs; await studioRequest(`${endpoint}/remote/jobs/${job}/actions`, "POST", { request_id: crypto.randomUUID(), kind, run_id, epochs: kind === "resume" ? resumeEpochs ?? epochs : epochs, text: sampleText }); setRemoteBusy(true); setNotice("Đã gửi tác vụ; tiến độ cập nhật từ Drive/Colab."); }); }
  const disabled = busy || remoteBusy;
  return <section className="space-y-5 rounded-xl border border-emerald-500/20 p-5"><h2 className="text-xl font-semibold">Điều khiển huấn luyện từ AIFlow</h2><p className="text-sm text-zinc-400">Bật Colab một lần, sau đó tải dữ liệu, duyệt transcript, train/resume và đổi giọng tại đây. Từng bước chỉ chạy khi bạn bấm.</p>
    <div className="flex flex-wrap gap-3"><a className={button} href="/api/training-control/notebook">Tải notebook điều khiển</a><a className={button} href="/api/training-control/worker-bundle">Tải gói worker</a></div>
    <form className="grid gap-3 sm:grid-cols-2" onSubmit={e => { e.preventDefault(); void act(async () => { await studioRequest(`${endpoint}/connection`, "PUT", { url, token }); setConnected(true); setToken(""); setNotice("Đã kết nối điều khiển. Chưa tải hay train."); }); }}><label>URL Colab<input className={field} type="url" required value={url} onChange={e => setUrl(e.target.value)} placeholder="https://….trycloudflare.com" /></label><label>Token phiên<input required type="password" autoComplete="off" className={field} value={token} onChange={e => setToken(e.target.value)} /></label><button disabled={busy} className={button}>Kiểm tra & kết nối điều khiển</button><button type="button" className={button} disabled={busy || !connected} onClick={() => void act(async () => { await studioRequest(`${endpoint}/connection`, "DELETE"); setConnected(false); setDetail(null); })}>Ngắt kết nối (không dừng Colab)</button></form>
    {error && <p role="alert" className="text-rose-300">{error}</p>}<p role="status" className="text-sm text-emerald-300">{busy ? "Đang xử lý…" : notice}</p>
    {connected && <><label className="block">Bộ dữ liệu đã gửi lên Drive<select disabled={busy} className={field} value={job} onChange={e => selectJob(e.target.value)}><option value="">Chọn bộ dữ liệu</option>{incomingJob && !jobs.some(j => j.job_id === incomingJob) && <option value={incomingJob}>{incomingJob}</option>}{jobs.map(j => <option key={j.job_id} value={j.job_id}>{j.voice_name} · {j.job_id.slice(0, 8)}</option>)}</select></label><p className="text-xs text-zinc-400">Chưa có bộ dữ liệu? Quét R2, chọn file rồi bấm Gửi lựa chọn sang Colab ở phần dưới.</p></>}
    {connected && detail && <><div className="flex flex-wrap items-center gap-2"><button className={button} disabled={disabled} onClick={() => void action("download")}>1. Tải đúng file đã chọn</button><button className={button} disabled={disabled} onClick={() => void action("prepare")}>2. Tách audio / chép lời</button><button className={button} disabled={busy || !detail.has_dataset} onClick={() => void act(readReview)}>3. Mở dataset để duyệt</button><label className="text-sm">Epochs <input className="w-16 rounded bg-zinc-900 p-2" type="number" min={1} max={20} value={epochs} onChange={e => setEpochs(Number(e.target.value))} /></label><button className={button} disabled={disabled || !detail.dataset_approved} onClick={() => void action("train")}>4. Train phiên bản mới</button><button className={button} disabled={busy || !remoteBusy} onClick={() => void act(async () => { await studioRequest(`${endpoint}/remote/jobs/${job}/cancel`, "POST", {}); setNotice("Đã yêu cầu dừng ở ranh giới an toàn; chờ Colab hoàn tất checkpoint."); })}>Yêu cầu dừng</button></div>
    <p className="text-sm">Colab: {remoteBusy ? "đang xử lý, không gửi thêm tác vụ" : "sẵn sàng"} · Dataset: {detail.dataset_approved ? "đã duyệt" : "chưa duyệt"}</p>
    <ul className="max-h-40 overflow-auto space-y-2 text-sm">{detail.actions.slice(0, 12).map(a => <li key={a.request_id}>{a.input.kind} · {a.status}{a.error && <span className="text-amber-200"> · {a.error}</span>}</li>)}</ul>
    {!!review.rows.length && edit && <div className="space-y-3 border-t border-white/10 pt-4"><h3 className="font-semibold">Nghe và sửa transcript</h3><select aria-label="Đoạn audio" className={field} value={index} onChange={e => { const i = Number(e.target.value); setIndex(i); setEdit(review.rows[i]); }}>{review.rows.map((r, i) => <option key={r.file} value={i}>{i + 1}. {r.reviewed ? "✓" : "Chưa duyệt"} · {r.duration.toFixed(1)}s · {r.source}</option>)}</select><audio key={edit.file} controls src={`/api${endpoint}/remote/jobs/${job}/clips/${encodeURIComponent(edit.file)}`} /><label className="block">Lời chép<textarea className={`${field} min-h-28`} value={edit.text} onChange={e => setEdit({ ...edit, text: e.target.value, reviewed: false })} /></label><label className="flex gap-2"><input type="checkbox" checked={edit.include} onChange={e => setEdit({ ...edit, include: e.target.checked })} />Dùng đoạn này</label><label className="flex gap-2"><input type="checkbox" checked={edit.reviewed} onChange={e => setEdit({ ...edit, reviewed: e.target.checked })} />Tôi đã nghe và sửa đúng lời / đúng người nói</label><button className={button} disabled={disabled} onClick={() => void act(async () => { const data = await studioRequest<typeof review>(`${endpoint}/remote/jobs/${job}/review`, "PUT", { hash: review.hash, file: edit.file, text: edit.text, include: edit.include, reviewed: edit.reviewed }); setReview(data); const next = Math.min(index + 1, data.rows.length - 1); setIndex(next); setEdit(data.rows[next]); })}>Lưu đoạn & tiếp</button><button className={`${button} ml-2`} disabled={disabled} onClick={() => void act(() => studioRequest(`${endpoint}/remote/jobs/${job}/approve-dataset`, "POST", { hash: review.hash }))}>Duyệt toàn bộ dataset đã lưu</button><p className="text-xs text-zinc-400">Tối thiểu 20 đoạn được dùng đã nghe/sửa. Bản sửa chưa lưu không tham gia huấn luyện.</p></div>}
    <label className="block">Câu nghe thử sau train<textarea className={field} maxLength={1500} value={sampleText} onChange={e => setSampleText(e.target.value)} /></label>
    {detail.runs.map(run => <article key={run.run_id} className="space-y-3 border-t border-white/10 pt-4"><h3>{run.profile?.name || "Lượt huấn luyện"} · {run.run_id.slice(0, 8)} · {run.profile?.status || "chưa đóng gói"}</h3>{run.progress && <p>Bước optimizer đã lưu: {run.progress.step}/{run.progress.total_steps}</p>}<div className="flex flex-wrap gap-2">{run.can_resume && <button className={button} disabled={disabled} onClick={() => void action("resume", run.run_id)}>Tiếp tục checkpoint (giữ epochs cũ)</button>}{run.profile && <button className={button} disabled={disabled || !sampleText.trim()} onClick={() => { setHeard(heard.filter(id => id !== run.run_id)); void action("sample", run.run_id); }}>Sinh mẫu nghe thử</button>}{run.profile?.status === "approved" && <button className={button} disabled={disabled} onClick={() => void action("load", run.run_id)}>Load / đổi sang giọng này</button>}</div>{run.has_sample && <><audio key={`${run.run_id}-${detail.actions[0]?.request_id}-${detail.actions[0]?.status}`} controls src={`/api${endpoint}/remote/jobs/${job}/runs/${run.run_id}/sample`} /><label className="flex gap-2 text-sm"><input type="checkbox" checked={heard.includes(run.run_id)} onChange={e => setHeard(e.target.checked ? [...heard, run.run_id] : heard.filter(id => id !== run.run_id))} />Đã nghe mẫu, đúng giọng và chất lượng dùng được</label><button className={button} disabled={disabled || !heard.includes(run.run_id)} onClick={() => void act(() => studioRequest(`${endpoint}/remote/jobs/${job}/runs/${run.run_id}/approve`, "POST", { heard: true }))}>Duyệt giọng</button></>}</article>)}
    <button className={button} disabled={disabled} onClick={() => void act(async () => { await studioRequest(`${endpoint}/use-audio`, "POST", {}); setNotice("Đã cập nhật giọng đang load vào Colab & audio. Có thể tạo lời đọc."); })}>Dùng giọng đang load cho TTS trong AIFlow</button></>}
  </section>;
}
