import { useCallback, useEffect, useRef, useState } from "react";
import { Link, NavLink, useSearchParams } from "react-router-dom";
import ProductionActions from "../components/ProductionActions";

const base = "/api/production";
const field = "w-full rounded-lg border border-white/15 bg-zinc-900 p-3 text-sm";
const button = "rounded-lg border border-white/20 px-4 py-2 text-sm hover:bg-white/10 disabled:opacity-40";
const panel = "rounded-xl border border-white/10 bg-zinc-900/40 p-5 space-y-4";
type Project = { id: number; title: string; kind: string; status: string; channel: string };
type Output = { id: number; project_id: number; kind: string; status: string; error?: string };
type Task = { id: number; project_id: number; status: string; type?: string; title?: string };
type Overview = { projects: Project[]; outputs: Output[]; jobs: Task[]; audio: Task[] };
type Media = { id: number; role: string; scene_id?: number; mime: string; approved: boolean; width: number; height: number };
type Detail = Project & { brief: Record<string, string>; prompt: string; media: Media[]; scenes: { id: number; order: number; prompt: string; narration: string; duration: number; has_audio: boolean }[] };
type Delivery = Output & { manifest: { files?: Record<string, { bytes: number }>; error?: string; actual_duration?: number } };

async function request<T>(path: string, method = "GET", body?: unknown): Promise<T> {
  const response = await fetch(base + path, { method, headers: { "X-AIFlow-Client": "1", ...(body instanceof FormData ? {} : { "Content-Type": "application/json" }) }, body: body instanceof FormData ? body : body === undefined ? undefined : JSON.stringify(body) });
  const result = await response.json();
  if (!response.ok) throw new Error(typeof result.detail === "string" ? result.detail : "Không xử lý được yêu cầu. Kiểm tra nội dung nhập.");
  return result;
}

export function WorkspaceNav() {
  return <header className="border-b border-white/10 px-4 py-3"><nav aria-label="Điều hướng xưởng" className="mx-auto flex max-w-7xl flex-wrap items-center gap-2 text-sm"><Link to="/" className="mr-4 font-semibold">AIFlow / Studio</Link>{[["/", "Tổng quan"], ["/scripts", "Kịch bản"], ["/production", "Sản xuất"], ["/connections", "Colab & audio"], ["/voice-training", "Huấn luyện giọng"], ["/studio-settings", "Kết nối & series"], ["/work-queue", "Tác vụ"], ["/library", "Thư viện"], ["/projects", "Dự án cũ"]].map(([to, label]) => <NavLink key={to} to={to} end className={({ isActive }) => `rounded-md px-3 py-2 ${isActive ? "bg-emerald-400/10 text-emerald-300" : "text-zinc-400 hover:text-white"}`}>{label}</NavLink>)}</nav></header>;
}

function Checklist({ entries, onSubmit, busy }: { entries: [string, string][]; onSubmit: (checklist: string[]) => void; busy: boolean }) {
  const [checked, setChecked] = useState<string[]>([]);
  return <div className="space-y-3">{entries.map(([id, label]) => <label key={id} className="flex items-start gap-3 text-sm"><input type="checkbox" checked={checked.includes(id)} onChange={e => setChecked(e.target.checked ? [...checked, id] : checked.filter(x => x !== id))} className="mt-1" />{label}</label>)}<button className={button} disabled={busy || checked.length !== entries.length} onClick={() => onSubmit(checked)}>Xác nhận đã kiểm tra</button></div>;
}

export default function ProductionStudio({ view = "production" }: { view?: "production" | "overview" | "queue" | "library" }) {
  const [params, setParams] = useSearchParams();
  const selected = Number(params.get("project")) || 0;
  const currentSelection = useRef(selected);
  currentSelection.current = selected;
  const [overview, setOverview] = useState<Overview>({ projects: [], outputs: [], jobs: [], audio: [] });
  const [detail, setDetail] = useState<Detail | null>(null);
  const [delivery, setDelivery] = useState<Delivery | null>(null);
  const [search, setSearch] = useState("");
  const [kind, setKind] = useState("");
  const [status, setStatus] = useState("");
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const [loading, setLoading] = useState(true);
  const [loop, setLoop] = useState(false);
  const [subtitleMode, setSubtitleMode] = useState("scene");
  const [stillMotion, setStillMotion] = useState(false);
  const [channel, setChannel] = useState("");
  const refresh = useCallback(async () => {
    setOverview(await request<Overview>("/overview"));
    const next = selected ? await request<Detail>(`/projects/${selected}`) : null;
    if (currentSelection.current === selected) setDetail(next);
  }, [selected]);
  useEffect(() => { let active = true; setLoading(true); setDetail(null); setDelivery(null); setLoop(false); refresh().catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setLoading(false); }); const timer = setInterval(() => { refresh().catch(() => {}); }, 5000); return () => { active = false; clearInterval(timer); }; }, [refresh]);
  useEffect(() => { setChannel(detail?.brief.channel || ""); }, [detail?.id]);
  async function act(action: () => Promise<unknown>) {
    setBusy(true); setError("");
    try { await action(); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Không hoàn tất thao tác."); } finally { setBusy(false); }
  }
  async function upload(file: File, role: string, scene?: number) {
    const form = new FormData(); form.set("file", file); form.set("role", role); if (scene) form.set("scene_id", String(scene));
    await request(`/projects/${selected}/media`, "POST", form);
  }
  function uploadControl(role: string, scene?: number) {
    return <label className="block space-y-2 text-sm text-zinc-300">{role === "reference" ? "Thêm ảnh tham chiếu (1–3 ảnh)" : role === "portrait" ? "Nhập chân dung đã tạo bằng dịch vụ AI bên ngoài" : "Nhập ảnh hoặc MP4 cho cảnh"}<input className={field} type="file" accept={role === "visual" ? "image/png,image/jpeg,image/webp,video/mp4" : "image/png,image/jpeg,image/webp"} disabled={busy || detail?.status === "generating"} onChange={e => { const file = e.target.files?.[0]; if (file) void act(() => upload(file, role, scene)); e.target.value = ""; }} /></label>;
  }
  function mediaCard(item: Media) {
    return <article key={item.id} className={panel}>{item.mime.startsWith("video") ? <video controls preload="metadata" src={`${base}/media/${item.id}`} className="max-h-80 w-full" /> : <img loading="lazy" src={`${base}/media/${item.id}`} alt={`${item.role === "reference" ? "Ảnh tham chiếu" : "Ảnh cần duyệt"} ${item.id}`} className="max-h-80 w-full object-contain" />}<p className="text-sm text-zinc-400">#{item.id} · {item.width} × {item.height}px · {item.approved ? "Đã duyệt" : item.role === "reference" ? "Tham chiếu" : "Chưa duyệt"}</p>{!item.approved && item.role !== "reference" && <Checklist busy={busy} entries={item.role === "portrait" ? [["likeness", "Đối chiếu bộ lông, màu mắt và dấu hiệu nhận diện với ảnh tham chiếu"], ["anatomy", "Mắt, tai, chân và giải phẫu đúng"], ["crop", "Bố cục và vùng cắt phù hợp"], ["artifacts", "Không có chi tiết lỗi hoặc chữ rác"]] : [["content", "Đúng nội dung cảnh"], ["continuity", "Nhân vật và bối cảnh liên tục"], ["framing", "Khung hình, giải phẫu và chi tiết đạt yêu cầu"]]} onSubmit={checklist => void act(() => request(`/media/${item.id}/review`, "POST", { checklist }))} />}<button className={button} disabled={busy || detail?.status === "generating"} onClick={() => void act(() => request(`/media/${item.id}`, "DELETE"))}>Lưu trữ bản này</button></article>;
  }
  const projects = overview.projects.filter(p => (!kind || p.kind === kind) && (!status || p.status === status) && `${p.title} ${p.channel}`.toLowerCase().includes(search.toLowerCase()));
  const outputs = overview.outputs.filter(o => !selected || o.project_id === selected);
  return <main className="mx-auto max-w-7xl space-y-7 px-4 py-8 pb-24 sm:px-8">
    <div><p className="text-xs uppercase tracking-widest text-emerald-400">Xưởng cá nhân · nhiều kênh</p><h1 className="mt-2 text-3xl font-semibold">{{ production: "Sản xuất & duyệt thành phẩm", overview: "Hôm nay cần làm gì?", queue: "Tác vụ & khôi phục", library: "Thư viện theo dự án" }[view]}</h1><p className="mt-3 max-w-3xl text-zinc-400">Duyệt kịch bản → chuẩn bị lời đọc và hình ảnh → xem thành phẩm → tải bộ file. Mỗi lượt xuất giữ một bản chụp dữ liệu riêng.</p></div>
    {error && <div role="alert" className="rounded-lg border border-rose-500/40 bg-rose-500/10 p-4">{error}<button className={`${button} ml-3`} onClick={() => void act(refresh)}>Thử tải lại</button></div>}
    {loading && <p role="status">Đang tải dữ liệu xưởng…</p>}
    {view === "library" && <div className="flex flex-wrap gap-3"><Link className={button} to="/voices">Thư viện giọng</Link><Link className={button} to="/new-project">Adapter & phong cách</Link><Link className={button} to="/scripts">Phiên bản kịch bản</Link></div>}{view === "overview" && <section className={panel}><h2 className="text-lg font-semibold">Việc đang chờ</h2><p>{overview.outputs.filter(o => o.status === "awaiting_review").length} thành phẩm chờ duyệt · {overview.audio.filter(a => a.status === "waiting_resource").length} tác vụ chờ Colab</p><div className="flex flex-wrap gap-3"><Link className={button} to="/scripts">Viết kịch bản</Link><Link className={button} to="/production">Làm chân dung / video</Link><Link className={button} to="/connections">Bật Colab và nhập URL</Link></div></section>}
    {view === "queue" ? <section className={panel}><label className="block">Lọc trạng thái<select value={status} onChange={e => setStatus(e.target.value)} className={field}><option value="">Tất cả</option>{Array.from(new Set([...overview.jobs, ...overview.audio].map(t => t.status))).map(s => <option key={s}>{s}</option>)}</select></label>{[...overview.audio.map(t => ({ ...t, group: "audio" })), ...overview.jobs.map(t => ({ ...t, group: "job" }))].filter(t => !status || t.status === status).map(t => <div className="flex flex-wrap items-center justify-between gap-3 border-t border-white/10 py-3" key={`${t.group}-${t.id}`}><div><p>{t.group} #{t.id} · {t.type || t.title}</p><p className="text-sm text-zinc-400">{t.status} · dự án {t.project_id || "audio độc lập"}</p></div><div className="flex gap-2"><Link className={button} to={t.group === "audio" ? "/queue" : `/production?project=${t.project_id}`}>Mở / thử lại</Link>{t.type === "production_render" && ["pending", "running"].includes(t.status) && <button className={button} disabled={busy} onClick={() => void act(() => request(`/jobs/${t.id}/cancel`, "POST"))}>Hủy sau công đoạn hiện tại</button>}</div></div>)}{!overview.audio.length && !overview.jobs.length && <p>Chưa có tác vụ. Tạo kịch bản hoặc dự án để bắt đầu.</p>}</section> : <>
    <section className={panel}><h2 className="text-lg font-semibold">Dự án</h2><div className="grid gap-3 sm:grid-cols-3"><input aria-label="Tìm dự án hoặc kênh" className={field} placeholder="Tìm tên dự án hoặc kênh…" value={search} onChange={e => setSearch(e.target.value)} /><select aria-label="Loại dự án" className={field} value={kind} onChange={e => setKind(e.target.value)}><option value="">Mọi loại</option><option value="portrait">Chân dung</option><option value="video">Video</option><option value="legacy">Chưa phân loại</option></select><select aria-label="Trạng thái dự án" className={field} value={status} onChange={e => setStatus(e.target.value)}><option value="">Mọi trạng thái</option>{Array.from(new Set(overview.projects.map(p => p.status))).map(s => <option key={s}>{s}</option>)}</select></div><div className="divide-y divide-white/10">{projects.map(p => <Link key={p.id} to={`/production?project=${p.id}`} className={`flex flex-wrap justify-between gap-2 py-3 ${selected === p.id ? "text-emerald-300" : ""}`}><span>{p.title} <small className="text-zinc-500">{p.channel || "Chưa gán kênh"}</small></span><span className="text-sm text-zinc-400">{p.kind} · {p.status}</span></Link>)}</div>{!projects.length && <p className="text-zinc-400">Chưa có dự án phù hợp.</p>}</section>
    {view === "production" && !selected && <section className={panel}><h2 className="text-xl font-semibold">Chân dung thú cưng mới</h2><p className="text-sm text-zinc-400">Tạo ảnh với Gemini đã cấu hình hoặc nhập kết quả từ dịch vụ khác, sau đó duyệt tại đây. AIFlow không chạy AI trên máy.</p><form className="grid gap-4 sm:grid-cols-2" onSubmit={e => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); void act(async () => { const result = await request<{ id: number }>("/portraits", "POST", data); setParams({ project: String(result.id) }); }); }}>{[["title", "Tên dự án"], ["channel", "Kênh / thương hiệu (tùy chọn)"], ["species", "Loài / giống thú cưng"], ["style", "Phong cách"], ["identity", "Đặc điểm nhận diện phải giữ"], ["requirements", "Yêu cầu giao hàng (tùy chọn)"]].map(([name, label]) => <label className="space-y-2 text-sm" key={name}>{label}<input name={name} className={field} maxLength={name === "identity" || name === "requirements" ? 5000 : name === "style" ? 1000 : name === "title" ? 200 : 100} required={!["channel", "requirements"].includes(name)} /></label>)}<button disabled={busy} className={button}>Tạo dự án chân dung</button><Link to="/scripts" className={button}>Tạo video từ kịch bản</Link></form></section>}
    {detail && <section className="space-y-5"><div className={panel}><h2 className="text-2xl font-semibold">{detail.title}</h2><p className="text-zinc-400">{detail.kind} · {detail.status}</p><label className="block text-sm">Kênh / thương hiệu<input value={channel} onChange={e => setChannel(e.target.value)} maxLength={100} className={field} /></label><button className={button} disabled={busy || detail.status === "generating"} onClick={() => void act(() => request(`/projects/${selected}/kind`, "PUT", { kind: detail.kind === "legacy" ? "video" : detail.kind, channel }))}>{detail.kind === "legacy" ? "Xác nhận đây là dự án video" : "Lưu kênh"}</button></div>
    <ProductionActions key={detail.id} projectId={detail.id} kind={detail.kind} scenes={detail.scenes} onChanged={refresh} />{detail.kind === "portrait" && <><section className={panel}><h3 className="font-semibold">1. Brief & ảnh tham chiếu</h3><pre className="whitespace-pre-wrap break-words text-sm text-zinc-300">{detail.prompt}</pre>{uploadControl("reference")}<div className="grid gap-4 md:grid-cols-3">{detail.media.filter(m => m.role === "reference").map(mediaCard)}</div></section><section className={panel}><h3 className="font-semibold">2. Thành phẩm & độ giống</h3>{uploadControl("portrait")}<p className="text-sm text-zinc-400">Bản mới nhất đang hiển thị đầu tiên sẽ được dùng để xuất. Đối chiếu với ảnh tham chiếu bên trên trước khi duyệt.</p><div className="grid gap-4 md:grid-cols-2">{detail.media.filter(m => m.role === "portrait").map(mediaCard)}</div></section></>}
    {detail.kind === "video" && <><div className="flex flex-wrap gap-3"><Link className={button} to="/connections">Chuẩn bị lời đọc trên Colab</Link><Link className={button} to={`/timeline/${selected}`}>Timeline / Flow</Link></div>{detail.scenes.map(scene => <section className={panel} key={scene.id}><h3 className="font-semibold">Cảnh {scene.order + 1} · {scene.duration}s theo kịch bản</h3><p className="text-sm text-zinc-300">{scene.prompt}</p><p className="text-sm text-zinc-400">{scene.narration || "Cảnh im lặng"} · {scene.has_audio ? "Có file audio; sẽ đo khi xuất" : scene.narration ? "Chưa có lời đọc" : "Không cần TTS"}</p>{uploadControl("visual", scene.id)}<div className="grid gap-4 md:grid-cols-2">{detail.media.filter(m => m.scene_id === scene.id).map(mediaCard)}</div></section>)}</>}
    {detail.kind !== "legacy" && <section className={panel}><h3 className="font-semibold">3. Xuất bản nháp để xem</h3>{detail.kind === "video" && <label className="block text-sm">Cách tạo phụ đề<select className={field} value={subtitleMode} onChange={e => setSubtitleMode(e.target.value)}><option value="scene">Theo cảnh và thời lượng lời đọc (không cần Colab)</option><option value="remote_stt">Nhận dạng trên Colab (cần bật STT)</option></select></label>}{detail.kind === "video" && <><p className="text-sm text-zinc-400">Dùng ảnh/clip mới nhất đã duyệt cho mỗi cảnh. Phụ đề theo cảnh và thời lượng audio thực tế. Giữ khoảng im lặng, không cắt lời đọc.</p><label className="flex gap-3 text-sm"><input type="checkbox" checked={loop} onChange={e => setLoop(e.target.checked)} />Cho phép lặp clip khi clip ngắn hơn lời đọc</label><label className="flex gap-3 text-sm"><input type="checkbox" checked={stillMotion} onChange={e => setStillMotion(e.target.checked)} />Chuyển động zoom nhẹ cho ảnh tĩnh (cắt tối đa 5% vùng rìa)</label></>}<button className={button} disabled={busy || detail.status === "generating"} onClick={() => void act(() => request(`/projects/${selected}/render`, "POST", { allow_loop: loop, subtitle_mode: subtitleMode, still_motion: stillMotion }))}>Xuất lượt mới</button><p className="text-xs text-zinc-500">Lượt xuất lỗi được giữ trong lịch sử; sửa tài nguyên rồi xuất lượt mới.</p></section>}</section>}
    </>}
    <section className={panel}><h2 className="text-xl font-semibold">Thành phẩm {selected ? `· dự án #${selected}` : "gần đây"}</h2>{outputs.map(o => <div key={o.id} className="flex flex-wrap items-center justify-between gap-3 border-t border-white/10 py-3"><div>#{o.id} · {o.kind} · {o.status}{o.error && <p className="text-sm text-rose-300">{o.error}</p>}</div><button className={button} disabled={busy} onClick={() => void act(async () => setDelivery(await request<Delivery>(`/outputs/${o.id}`)))}>Xem và duyệt</button></div>)}{!outputs.length && <p className="text-zinc-400">Chưa có thành phẩm. Bộ file chỉ tải được sau bước duyệt cuối.</p>}</section>
    {delivery && <section className={panel}><h2 className="text-xl font-semibold">Duyệt bộ file #{delivery.id}</h2><p>{delivery.status}</p>{delivery.manifest.error && <p role="alert">{delivery.manifest.error}</p>}{delivery.manifest.files && <><div>{delivery.kind === "video" ? <video controls className="mx-auto max-h-[65vh] max-w-full" src={`${base}/outputs/${delivery.id}/file/video.mp4`} /> : <img className="mx-auto max-h-[65vh] max-w-full" alt="Bản xem trước thành phẩm" src={`${base}/outputs/${delivery.id}/file/preview.jpg`} />}</div><ul className="space-y-2 text-sm">{Object.entries(delivery.manifest.files).map(([name, info]) => <li key={name}><a className="text-emerald-300 underline" target="_blank" rel="noreferrer" href={`${base}/outputs/${delivery.id}/file/${name}`}>{name}</a> · {Math.ceil(info.bytes / 1024)} KB</li>)}</ul>{delivery.status === "awaiting_review" && <Checklist key={delivery.id} busy={busy} entries={[["quality", "Đã xem / nghe thành phẩm, không lỗi hình hoặc tiếng"], ["rights", "Có quyền sử dụng và giao các tài nguyên này"], ["delivery", "Đã kiểm tra bộ file, kích thước, phụ đề và nội dung mô tả"]]} onSubmit={checklist => void act(async () => { await request(`/outputs/${delivery.id}/review`, "POST", { checklist }); setDelivery(await request<Delivery>(`/outputs/${delivery.id}`)); })} />}{delivery.status === "approved" && <a className={button} href={`${base}/outputs/${delivery.id}/download`}>Tải ZIP đã duyệt</a>}</>}</section>}
  </main>;
}
